### ISSUE TITLE
Recommendations：Why not Clouflare Pages？

### ISSUE THREAD

**Issue by Initial-heart-1** [AmiyaBot/Amiya-Bot-docs#1]
Damn GitHub actions！

**Comment by vivien8261** [comment]
> Damn GitHub actions！

Github pages yes!

**Comment by Initial-heart-1** [comment]
> > Damn GitHub actions！
> 
> Github pages yes!

擦，大哥
github pages 我记得没法跑 vue 构建，是我孤陋寡闻了吗

**Comment by vivien8261** [comment]
> > > Damn GitHub actions！
> > 
> > 
> > Github pages yes!
> 
> 擦，大哥 github pages 我记得没法跑 vue 构建，是我孤陋寡闻了吗

这不是在跑了吗

**Comment by Initial-heart-1** [comment]
> > > > Damn GitHub actions！
> > > 
> > > 
> > > Github pages yes!
> > 
> > 
> > 擦，大哥 github pages 我记得没法跑 vue 构建，是我孤陋寡闻了吗
> 
> 这不是在跑了吗

那是 acitons！
![image](https://user-images.githubusercontent.com/63091661/175279334-b839a8e0-be67-49c8-a013-40f2b22f836e.png)

**Comment by vivien8261** [comment]
（不套娃了）那Vue构建指的什么

**Comment by Initial-heart-1** [comment]
> （不套娃了）那Vue构建指的什么

`npm run build`

**Comment by vivien8261** [comment]
问题是我不 run build 哪来的 gh-pages 分支……当然是可以的啊

**Comment by Initial-heart-1** [comment]
> 

不是由 actions 去 run build + 发布么

**Comment by vivien8261** [comment]
> > 
> 
> 不是由 actions 去 run build + 发布么

不就够了吗，你还想在哪里build

**Comment by Initial-heart-1** [comment]
> > > 
> > 
> > 
> > 不是由 actions 去 run build + 发布么
> 
> 不就够了吗，你还想在哪里build

我的意思是，Cloudflare Pages 可以一次性完成构建+发布且用时比 Github 至少少半分钟（样本只有一个，Amiya-Bot 官网（3wdotamiyadotcn）），不在特别高峰的高峰期的话甚至不需要排队上去就构建
而且最重要的是，Free！

**Comment by Initial-heart-1** [comment]
**不要小看半分钟！**
半分钟足够让 Cloudflare 位于全球各地的数据中心重新刷新对某网站的全部缓存
Cloudflare 有多少数据中心？让我看看......懒得数了，https://www.cloudflarestatus.com/
而且是部署在全球的数据中心，也就是 CDN

**Comment by vivien8261** [comment]
就几百kb的一个文档页面……我拿我5m小水管服务器都绰绰有余，就要这个就要这个，github yes

**Comment by Initial-heart-1** [comment]
> 就几百kb的一个文档页面……我拿我5m小水管服务器都绰绰有余，就要这个就要这个，github yes

擦，大哥
![image](https://user-images.githubusercontent.com/63091661/175283257-341c9c36-15f7-4593-b715-69e7452c6d68.png)
（虽然90%以上是字体......等会，兔妈你没开gzip🐎（对于字体））
